// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addFood": {
            "get": {
                "tags": [
                    "添加食物"
                ],
                "summary": "传入食物名称和价格",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入食物名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "请输入食物价格",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/deleteFood": {
            "post": {
                "tags": [
                    "删除食物"
                ],
                "summary": "传入吧",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
